CoreDemo/Controllers/AboutController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Mvc;

namespace CoreDemo.Controllers
{
	public class AboutController : Controller
	{
		AboutManager _abm=new AboutManager(new EFAboutRepository());
		public IActionResult Index()
		{
			var values = _abm.GetList();
			return View(values);
		}

		public PartialViewResult SocialMediaAbout()
		{
			return PartialView();
		}
	}
}

CoreDemo/Controllers/ContactController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ApplicationModels;

namespace CoreDemo.Controllers
{
	public class ContactController : Controller
	{
		ContactManager cm = new ContactManager(new EFContactRepository());

		[HttpGet]
		public IActionResult Index()
		{
			return View();
		}
		[HttpPost]
		public IActionResult Index(Contact c)
		{
			c.ContactDate= DateTime.Parse(DateTime.Now.ToShortDateString());
			c.ContactStatus = true;
			cm.ContactAdd(c);
			return RedirectToAction("Index","Blog");
		}
	}
}

CoreDemo/Controllers/LoginController.cs
using DataAccessLayer.Concrete;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace CoreDemo.Controllers
{
    public class LoginController : Controller
    {
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Index(Writer w)
        {
           Context c= new Context();
            var dataValue=c.Writers.FirstOrDefault(x=>x.WriterMail==w.WriterMail && x.WriterPassword==w.WriterPassword);
            if (dataValue!=null)
            {
                var claims=new List<Claim> 
                { 
                    new Claim(ClaimTypes.Name,w.WriterMail)
                };
                var userIdentity=new ClaimsIdentity(claims,"a");
                ClaimsPrincipal principal=new ClaimsPrincipal(userIdentity);
                await HttpContext.SignInAsync(principal);
                return RedirectToAction("Index","Writer");
            }
            else
                return View();
        }
    }
}

//Context c = new Context();
//var dataValue = c.Writers.FirstOrDefault(x => x.WriterMail == w.WriterMail && x.WriterPassword == w.WriterPassword);
//if (dataValue != null)
//{
//    HttpContext.Session.SetString("username", w.WriterMail);
//    return RedirectToAction("Index", "Writer");
//}
//else
//    return View();

CoreDemo/Controllers/RegisterController.cs
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Mvc;
using BusinessLayer.Concrete;
using EntityLayer.Concrete;
using Microsoft.Identity.Client.Utils.Windows;
using CoreDemo.Helper;
using CoreDemo.Models.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using BusinessLayer.ValidationRules;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace CoreDemo.Controllers
{
	public class RegisterController : Controller
	{
		WriterManager wm=new WriterManager(new EFWriterRepository());

		[HttpGet]
		public IActionResult Index()
		{
			callList();
			return View();
		}

		[HttpPost]
		public IActionResult Index(Writer w)
		{
			WriterValidator WV= new WriterValidator();
			ValidationResult result=WV.Validate(w);
			if(result.IsValid)
			{
                w.WriterStatus = true;
				if(w.WriterImage==null)
				{
					w.WriterImage = "Standart Profil Fotoğrafı";
				}
                wm.AddT(w);
                return RedirectToAction("Index", "Blog");
            }
			else
			{
                ModelState.Clear();
                foreach (var item in result.Errors)
				{						
						ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
				}
			}
			callList();
			return View();
		}

		public void callList()
		{
            var cities = Cities.GetAll();
            var model = new RegisterViewModel();
            model.CitiesSelectList = new List<SelectListItem>();

            foreach (var city in cities)
            {
                model.CitiesSelectList.Add(new SelectListItem { Text = city.Name, Value = city.Id.ToString() });
            }
            ViewData["Cities"] = model.CitiesSelectList;
        }
	}
}

CoreDemo/Views/Shared/Partial1.cshtml
<div class="header_top" id="home">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right mx-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Blog" asp-action="Index">
                        Ana Sayfa
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="About" asp-action="Index">Hakkımızda</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Blog" asp-action="Index">Bloglar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Contact" asp-action="Index">İletişim</a>
                </li>

            </ul>
            <form action="#" method="post" class="form-inline my-2 my-lg-0 header-search">
                <input class="form-control mr-sm-2" type="search" placeholder="Aranacak Kelime" name="Search" required="">
                <button class="btn btn1 my-2 my-sm-0" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </form>



        </div>
    </nav>

</div>

CoreDemo/Views/Shared/Partial2.cshtml
<div class="col-md-4 top-forms text-center mt-lg-3 mt-md-1 mt-0">
					<span>Hoş Geldin</span>
					<span class="mx-lg-4 mx-md-2  mx-1">
						<a asp-controller="Login" asp-action="Index">
							<i class="fas fa-lock"></i> Giriş Yap
						</a>
					</span>
					<span>
						<a asp-controller="Register" asp-action="Index">
							<i class="far fa-user"></i> Kayıt Ol
						</a>
					</span>
				</div>

CoreDemo/Views/Shared/Partial3.cshtml
<footer>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-4 footer-grid-agileits-w3ls text-left">
                <h3>Hakkımızda</h3>
                <p>Blog (Türkçe: ağ günlüğü, günce) veya Weblog (Türkçe: Ağ kütüğü) teknik bilgi gerektirmeden, kendi istedikleri şeyleri, kendi istedikleri şekilde yazan insanların oluşturabildikleri, günlüğe benzeyen web siteleridir. Genellikle güncelden eskiye doğru sıralanmış yazı ve yorumların yayınlandığı, web tabanlı bir yayını belirtir...</p>
                <div class="read">
                    <a asp-controller="About" asp-action="Index" class="btn btn-primary read-m">Devamını Oku</a>
                </div>
            </div>
            <div class="col-lg-4 footer-grid-agileits-w3ls text-left">

                @await Component.InvokeAsync("BlogLast3Post");
            </div>
            <!-- subscribe -->
            <div class="col-lg-4 subscribe-main footer-grid-agileits-w3ls text-left">
                <h2>Bültenimize abone olabilirsiniz</h2>
                <p>Teknoloji, Yazılım, Doğa, Oyunlar ve birçok konu başlığında bloglarımıza önceden erişebilir ve okuyabilirsiniz </p>
                <div class="subscribe-main text-left">
                    <div class="subscribe-form">
                        <form asp-action="SubscribeMail" asp-controller="Newsletter" method="post" class="subscribe_form">
                            <input class="form-control" type="email" name="Mail" placeholder="E-posta" required="">
                            <button type="submit" class="btn btn-primary submit">Abone Ol</button>
                        </form>
                        <div class="clearfix"></div>
                        <!-- //subscribe -->
                    </div>
                </div>
            </div>
            <!-- footer -->
            <div class="footer-cpy text-center">
                <div class="footer-social">
                    <div class="copyrighttop">
                        <ul>
                            <li class="mx-3">
                                <a class="facebook" href="#">
                                    <i class="fab fa-facebook-f"></i>
                                    <span>Facebook</span>
                                </a>
                            </li>
                            <li>
                                <a class="facebook" href="#">
                                    <i class="fab fa-twitter"></i>
                                    <span>Twitter</span>
                                </a>
                            </li>
                            <li class="mx-3">
                                <a class="facebook" href="#">
                                    <i class="fab fa-google-plus-g"></i>
                                    <span>Google+</span>
                                </a>
                            </li>
                            <li>
                                <a class="facebook" href="#">
                                    <i class="fab fa-pinterest-p"></i>
                                    <span>Pinterest</span>
                                </a>
                            </li>
                        </ul>

                    </div>
                </div>
                <div class="w3layouts-agile-copyrightbottom">
                    <p>
                        @DateTime.Now.Year Asp.Net Core 5.0 Proje Kampı | Tüm Hakları Saklıdır | Design by
                        <a class="design-owner" href="http://w3layouts.com/">W3layouts</a>
                    </p>

                </div>
            </div>


        </div>
</footer>

CoreDemo/Views/Shared/UserLayout.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<html lang="zxx">

<head>
    <title>Blogia Blog Page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" />
    @*<script src="~/lib/jquery/dist/jquery.js"></script>*@
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>

    <link href="~/CoreBlogTema/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="~/CoreBlogTema/css/single.css">
    <link href="~/CoreBlogTema/css/style.css" rel='stylesheet' type='text/css' />
    <link href="~/CoreBlogTema/css/fontawesome-all.css" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800"
          rel="stylesheet">
</head>

<body>
    <!--Header-->

    <header>
        <div class="top-bar_sub_w3layouts container-fluid">
            <div class="row">
                <div class="col-md-4 logo text-left">
                    <a class="navbar-brand" asp-controller="Writer" asp-action="Index">
                        <i class="fab fa-linode"></i> Blogia
                    </a>
                </div>
                @await Html.PartialAsync("Partial2")
                <div class="col-md-4 log-icons text-right">

                    <ul class="social_list1 mt-3">

                        <li>
                            <a href="#" class="facebook1 mx-2">
                                <i class="fab fa-facebook-f"></i>

                            </a>
                        </li>
                        <li>
                            <a href="#" class="twitter2">
                                <i class="fab fa-twitter"></i>

                            </a>
                        </li>
                        <li>
                            <a href="#" class="dribble3 mx-2">
                                <i class="fab fa-dribbble"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="pin">
                                <i class="fab fa-pinterest-p"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        @await Html.PartialAsync("Partial1");
    </header>
    <!--//header-->
    <!--/banner-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="index.html">Home</a>
        </li>
        <li class="breadcrumb-item active">
            @switch (ViewContext.RouteData.Values["controller"].ToString())
            {
                case "About":
                    <a>Hakkımızda</a>
                    ; break;
                case "Blog":
                    <a>Bloglar</a>
                    ; break;
                case "Contact":
                    <a>İletişim</a>
                    ; break;

            }
        </li>
    </ol>
    <!--//banner-->
    <!--/main-->
    @RenderBody()
    <!--//main-->
    <!--footer-->
    @await Html.PartialAsync("Partial3")
    <!-- //footer -->
    <!---->
    <!-- js -->

    <script src="~/CoreBlogTema/js/jquery-2.2.3.min.js"></script>
    <!-- //js -->
    <!--/ start-smoth-scrolling -->
    <script src="~/CoreBlogTema/js/move-top.js"></script>
    <script src="~/CoreBlogTema/js/easing.js"></script>
    <script>
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({
                    scrollTop: $(this.hash).offset().top
                }, 900);
            });
        });
    </script>
    <!--// end-smoth-scrolling -->

    <script>
        $(document).ready(function () {
            /*
                                    var defaults = {
                                            containerID: 'toTop', // fading element id
                                        containerHoverID: 'toTopHover', // fading element hover id
                                        scrollSpeed: 1200,
                                        easingType: 'linear'
                                        };
                                    */

            $().UItoTop({
                easingType: 'easeOutQuart'
            });

        });
    </script>
    <a href="#home" class="scroll" id="toTop" style="display: block;">
        <span id="toTopHover" style="opacity: 1;"> </span>
    </a>

    <!-- //Custom-JavaScript-File-Links -->
    <script src="~/CoreBlogTema/js/bootstrap.js"></script>


</body>

</html>

CoreDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CoreDemo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoreDemo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Test">Help</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CoreDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>